# This file contains the test cases for each environment that are available for the application.

environments:
  - DEV:
      tests:
        - name: smoke-tests
          scripts:
            - tests/smoke_test.sh
        - name: regression-tests
          scripts:
            - tests/regression_test.sh
  - QA:
      tests:
        - name: smoke-tests
          scripts:
            - tests/smoke_test.sh

        - name: regression-tests
          scripts:
            - tests/regression_test.sh

        - name: integration-tests
          scripts:
            - tests/integration_test.sh

        - name: performance-tests
          scripts:
            - tests/performance_test.sh

        # UAT tests are manual, the pipeline will tag this test as PENDING ([major].[minor].[patch]/CD/QA/uat-tests/PENDING) and promotion to PROD is
        # only possible after the test is passed indicated by a tag of the form [major].[minor].[patch]/CD/QA/uat-tests/PASS. Pushing this tag will trigger
        # the trigger the verify-and-tag workflow which will tag the environment as passed ([major].[minor].[patch]/CD/QA/PASS) and hence trigger the
        # conditional-deploy workflow, which in turn will call the deployment pipeline.
        - name: uat-tests

  - PROD:
      tests:
        - name: smoke-tests
          scripts:
            - tests/smoke_test.sh